# -*- coding: utf-8 -*-
"""Build a static GitHub Pages site for DSA reports.

The generated site is intentionally dependency-free so it can run in GitHub
Actions after the daily analysis job. It publishes a report dashboard at the
Pages root and, when provided, copies the full React WebUI under /app/.
"""

from __future__ import annotations

import argparse
import html
import shutil
from datetime import datetime, timezone
from pathlib import Path


REPORT_SUFFIXES = {".md", ".markdown", ".txt", ".html", ".json"}


def _clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _copy_tree_contents(source: Path, target: Path) -> None:
    if not source.exists():
        return
    target.mkdir(parents=True, exist_ok=True)
    for item in source.iterdir():
        destination = target / item.name
        if item.is_dir():
            shutil.copytree(item, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(item, destination)


def _find_reports(reports_dir: Path) -> list[Path]:
    if not reports_dir.exists():
        return []
    reports = [
        path
        for path in reports_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in REPORT_SUFFIXES
    ]
    return sorted(reports, key=lambda path: path.stat().st_mtime, reverse=True)


def _relative_posix(path: Path, base: Path) -> str:
    return path.relative_to(base).as_posix()


def _safe_html_name(relative_path: str) -> str:
    return "".join(ch if ch.isalnum() else "-" for ch in relative_path).strip("-") + ".html"


def _render_report_html(title: str, content: str, raw_href: str) -> str:
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)} - DSA Report</title>
  <link rel="stylesheet" href="../styles.css">
</head>
<body>
  <main class="page">
    <nav class="topbar">
      <a href="../index.html">Report Dashboard</a>
      <a href="../app/">Full WebUI</a>
      <a href="{html.escape(raw_href)}">Raw File</a>
    </nav>
    <article class="report">
      <h1>{html.escape(title)}</h1>
      <pre>{html.escape(content)}</pre>
    </article>
  </main>
</body>
</html>
"""


def _render_index(report_items: list[dict[str, str]], generated_at: str, has_app: bool) -> str:
    rows = "\n".join(
        f"""        <tr>
          <td><a href="{html.escape(item['html_href'])}">{html.escape(item['name'])}</a></td>
          <td>{html.escape(item['modified'])}</td>
          <td><a href="{html.escape(item['raw_href'])}">raw</a></td>
        </tr>"""
        for item in report_items
    )
    if not rows:
        rows = """        <tr>
          <td colspan="3" class="empty">No reports have been generated yet. Run the daily analysis workflow first.</td>
        </tr>"""

    app_link = '<a class="button secondary" href="app/">Open Full WebUI</a>' if has_app else ""

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DSA Report Dashboard</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <main class="page">
    <section class="hero">
      <p class="eyebrow">Daily Stock Analysis</p>
      <h1>Report Dashboard</h1>
      <p class="lead">Static GitHub Pages dashboard generated by GitHub Actions.</p>
      <div class="actions">
        <a class="button" href="reports/">Browse Reports</a>
        {app_link}
      </div>
    </section>

    <section class="panel">
      <div class="panel-header">
        <h2>Latest Reports</h2>
        <span>Generated at {html.escape(generated_at)}</span>
      </div>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Report</th>
              <th>Updated</th>
              <th>File</th>
            </tr>
          </thead>
          <tbody>
{rows}
          </tbody>
        </table>
      </div>
    </section>
  </main>
</body>
</html>
"""


def _write_styles(output_dir: Path) -> None:
    (output_dir / "styles.css").write_text(
        """
:root {
  color-scheme: dark;
  --bg: #0b1018;
  --panel: #101826;
  --panel-2: #142033;
  --text: #e6edf7;
  --muted: #9aa8ba;
  --line: #26364d;
  --accent: #27c7b8;
  --accent-2: #e7b85c;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  min-height: 100vh;
  background: var(--bg);
  color: var(--text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
a { color: inherit; }
.page {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 40px 0 56px;
}
.hero {
  padding: 36px 0 28px;
  border-bottom: 1px solid var(--line);
}
.eyebrow {
  margin: 0 0 10px;
  color: var(--accent);
  font-size: 13px;
  font-weight: 700;
  letter-spacing: 0;
  text-transform: uppercase;
}
h1 {
  margin: 0;
  font-size: clamp(36px, 6vw, 68px);
  line-height: 1;
  letter-spacing: 0;
}
.lead {
  max-width: 680px;
  margin: 18px 0 0;
  color: var(--muted);
  font-size: 17px;
  line-height: 1.65;
}
.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 26px;
}
.button {
  display: inline-flex;
  align-items: center;
  min-height: 42px;
  padding: 0 16px;
  border: 1px solid color-mix(in srgb, var(--accent) 55%, transparent);
  border-radius: 8px;
  background: color-mix(in srgb, var(--accent) 18%, transparent);
  color: var(--text);
  font-weight: 700;
  text-decoration: none;
}
.button.secondary {
  border-color: var(--line);
  background: var(--panel-2);
}
.panel {
  margin-top: 28px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
  overflow: hidden;
}
.panel-header {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  padding: 18px 20px;
  border-bottom: 1px solid var(--line);
}
.panel-header h2 {
  margin: 0;
  font-size: 18px;
}
.panel-header span {
  color: var(--muted);
  font-size: 13px;
}
.table-wrap { overflow-x: auto; }
table {
  width: 100%;
  border-collapse: collapse;
}
th, td {
  padding: 14px 20px;
  border-bottom: 1px solid var(--line);
  text-align: left;
  vertical-align: top;
}
th {
  color: var(--muted);
  font-size: 12px;
  text-transform: uppercase;
}
td a {
  color: var(--accent);
  font-weight: 650;
  text-decoration: none;
}
.empty {
  color: var(--muted);
}
.topbar {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-bottom: 20px;
}
.topbar a {
  padding: 8px 12px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
  color: var(--text);
  font-size: 14px;
  text-decoration: none;
}
.report {
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
  overflow: hidden;
}
.report h1 {
  padding: 22px 24px;
  border-bottom: 1px solid var(--line);
  font-size: 24px;
}
pre {
  margin: 0;
  padding: 24px;
  overflow-x: auto;
  white-space: pre-wrap;
  color: #d7e2f0;
  font: 14px/1.75 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}
@media (max-width: 640px) {
  .page { width: min(100% - 20px, 1120px); padding-top: 22px; }
  .panel-header { flex-direction: column; }
  th, td { padding: 12px; }
}
""".strip()
        + "\n",
        encoding="utf-8",
    )


def build_site(output_dir: Path, reports_dir: Path, app_dir: Path | None) -> None:
    _clean_dir(output_dir)
    _write_styles(output_dir)

    has_app = bool(app_dir and app_dir.exists())
    if has_app and app_dir:
        _copy_tree_contents(app_dir, output_dir / "app")

    reports_output = output_dir / "reports"
    raw_output = reports_output / "raw"
    html_output = reports_output / "html"
    raw_output.mkdir(parents=True, exist_ok=True)
    html_output.mkdir(parents=True, exist_ok=True)

    report_items: list[dict[str, str]] = []
    for report_path in _find_reports(reports_dir):
        relative = _relative_posix(report_path, reports_dir)
        raw_target = raw_output / relative
        raw_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(report_path, raw_target)

        html_name = _safe_html_name(relative)
        content = report_path.read_text(encoding="utf-8", errors="replace")
        raw_href_from_html = f"../raw/{relative}"
        (html_output / html_name).write_text(
            _render_report_html(relative, content, raw_href_from_html),
            encoding="utf-8",
        )

        modified = datetime.fromtimestamp(report_path.stat().st_mtime, timezone.utc)
        report_items.append(
            {
                "name": relative,
                "modified": modified.strftime("%Y-%m-%d %H:%M UTC"),
                "raw_href": f"reports/raw/{relative}",
                "html_href": f"reports/html/{html_name}",
            }
        )

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    index_html = _render_index(report_items, generated_at, has_app)
    (output_dir / "index.html").write_text(index_html, encoding="utf-8")
    (reports_output / "index.html").write_text(
        index_html.replace('href="reports/', 'href="').replace('href="app/', 'href="../app/'),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="pages-site")
    parser.add_argument("--reports", default="reports")
    parser.add_argument("--app", default="")
    args = parser.parse_args()

    app_dir = Path(args.app).resolve() if args.app else None
    build_site(
        output_dir=Path(args.output).resolve(),
        reports_dir=Path(args.reports).resolve(),
        app_dir=app_dir,
    )


if __name__ == "__main__":
    main()
